custom: 
  service: ${file(env.yml):service}
  serverless-offline:
    port: 8000
  customDomain: 
    domainName: ${file(env.yml):customDomain.${opt:stage, 'dev'}DomainName}
    certificateName: ${file(env.yml):customDomain.${opt:stage, 'dev'}CertificateName}
    basePath: ${file(env.yml):customDomain.${opt:stage, 'dev'}BasePath}
    stage: ${opt:stage, 'dev'}
    createRoute53Record: ${file(env.yml):customDomain.${opt:stage, 'dev'}CreateRoute53Record}

service: ${self:custom.service}

frameworkVersion: ">=1.23.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  memorySize: 128
  profile: ${self:custom.awsProfile} # aws named profile
  stage: ${opt:stage, 'dev'} # `sls deploy --stage production` if --stage is provided, else use dev
  stackTags: # Optional CF stack tags
    Name: ${self:custom.awsTagName}
    Stage: ${opt:stage, 'dev'}
  environment:
    bundleHash: ${opt:bundleHash}
    assetDomainName: ${file(env.yml):assetDomainName}

functions:
  renderHtml:
    handler: handler.render
    tags:
      Name: ${self:custom.awsTagName}
      Stage: ${opt:stage, 'dev'}
    events:
      - http:
          path: '{proxy+}'
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-domain-manager